# =============================================
# FuelTune Streamlit - Helm Chart
# =============================================

apiVersion: v2
name: fueltune
description: A Helm chart for FuelTune Streamlit application
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - fueltune
  - streamlit
  - automotive
  - data-analysis
  - fueltech

home: https://github.com/fueltune/streamlit
sources:
  - https://github.com/fueltune/streamlit

maintainers:
  - name: FuelTune Team
    email: team@fueltune.com

annotations:
  category: Analytics
  licenses: MIT
  images: |
    - name: fueltune-streamlit
      image: ghcr.io/fueltune/streamlit:1.0.0

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
  
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache
  
  - name: prometheus
    version: "25.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
    tags:
      - monitoring
  
  - name: grafana
    version: "7.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
    tags:
      - monitoring