# =============================================
# FuelTune Streamlit - Kubernetes Deployment
# =============================================
# Production-ready deployment with auto-scaling and zero-downtime updates

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fueltune-app
  namespace: fueltune
  labels:
    app: fueltune
    component: streamlit-app
    version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fueltune
      component: streamlit-app
  template:
    metadata:
      labels:
        app: fueltune
        component: streamlit-app
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8501"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: fueltune-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      # =============================================
      # Init Containers
      # =============================================
      initContainers:
      - name: wait-for-db
        image: postgres:15-alpine
        command:
          - sh
          - -c
          - |
            until pg_isready -h postgres-service -p 5432 -U fueltune; do
              echo "Waiting for PostgreSQL to be ready..."
              sleep 2
            done
            echo "PostgreSQL is ready!"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: fueltune-secrets
              key: postgres-password

      # =============================================
      # Application Container
      # =============================================
      containers:
      - name: fueltune-app
        image: fueltune/streamlit:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
          name: http
          protocol: TCP
        
        # =============================================
        # Environment Configuration
        # =============================================
        env:
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: APP_ENV
          value: "production"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
          value: "false"
        
        # Database connection
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fueltune-secrets
              key: database-url
        
        # Redis connection
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: fueltune-secrets
              key: redis-url
        
        # Pod metadata
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
        # =============================================
        # Resource Management
        # =============================================
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        
        # =============================================
        # Health Checks
        # =============================================
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        startupProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12
          successThreshold: 1
        
        # =============================================
        # Volume Mounts
        # =============================================
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
        - name: cache-volume
          mountPath: /app/cache
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        
        # =============================================
        # Security Context
        # =============================================
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      
      # =============================================
      # Volumes
      # =============================================
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: fueltune-data-pvc
      - name: logs-volume
        emptyDir:
          sizeLimit: "1Gi"
      - name: cache-volume
        emptyDir:
          sizeLimit: "500Mi"
      - name: config-volume
        configMap:
          name: fueltune-config
      
      # =============================================
      # Pod Scheduling
      # =============================================
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fueltune
                - key: component
                  operator: In
                  values:
                  - streamlit-app
              topologyKey: kubernetes.io/hostname
      
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      
      # =============================================
      # DNS Policy
      # =============================================
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30