"""add_vehicle_model_and_relationships_batch

Revision ID: 20c1d4d1f5bb
Revises: 
Create Date: 2025-09-06 18:07:48.205825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c1d4d1f5bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_data_sessions_vehicle_id', 'vehicles', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_sessions_vehicle_id', type_='foreignkey')

    # ### end Alembic commands ###
